#############################################################################
# Makefile for building: kkServer
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  kkServer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile kkServer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/qt/5.6/gcc_64/include -I/usr/local/qt/5.6/gcc_64/include/QtGui -I/usr/local/qt/5.6/gcc_64/include/QtNetwork -I/usr/local/qt/5.6/gcc_64/include/QtSql -I/usr/local/qt/5.6/gcc_64/include/QtCore -I. -I/usr/local/qt/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kkServer1.0.0
DISTDIR = /home/test999/pro/kkServer3/.tmp/kkServer1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,origin -Wl,-rpath,\$$ORIGIN -Wl,-rpath,/usr/local/qt/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -ltufao1 -lhiredis -L/usr/local/qt/5.6/gcc_64/lib -lQt5Gui -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		server.cpp \
		log.cpp \
		order.cpp \
		dbop.cpp moc_server.cpp
OBJECTS       = main.o \
		server.o \
		log.o \
		order.o \
		dbop.o \
		moc_server.o
DIST          = /usr/local/qt/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/linux.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/qconfig.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/resources.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/moc.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/lex.prf \
		kkServer.pro server.h \
		def.h \
		unit.h \
		log.h \
		order.h \
		dbop.h main.cpp \
		server.cpp \
		log.cpp \
		order.cpp \
		dbop.cpp
QMAKE_TARGET  = kkServer
DESTDIR       = 
TARGET        = kkServer


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kkServer.pro /usr/local/qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf /usr/local/qt/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/linux.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/qconfig.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/spec_post.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/qt.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/resources.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/moc.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/qt/5.6/gcc_64/mkspecs/features/lex.prf \
		kkServer.pro \
		/usr/local/qt/5.6/gcc_64/lib/libQt5Gui.prl \
		/usr/local/qt/5.6/gcc_64/lib/libQt5Network.prl \
		/usr/local/qt/5.6/gcc_64/lib/libQt5Sql.prl \
		/usr/local/qt/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile kkServer.pro
/usr/local/qt/5.6/gcc_64/mkspecs/features/spec_pre.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/unix.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/linux.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/sanitize.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-base.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/qconfig.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_functions.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/qt_config.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/spec_post.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/default_pre.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/resolve_config.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/default_post.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/warn_on.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/qt.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/resources.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/moc.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/opengl.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/unix/thread.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/exceptions.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/yacc.prf:
/usr/local/qt/5.6/gcc_64/mkspecs/features/lex.prf:
kkServer.pro:
/usr/local/qt/5.6/gcc_64/lib/libQt5Gui.prl:
/usr/local/qt/5.6/gcc_64/lib/libQt5Network.prl:
/usr/local/qt/5.6/gcc_64/lib/libQt5Sql.prl:
/usr/local/qt/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile kkServer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents server.h def.h unit.h log.h order.h dbop.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp server.cpp log.cpp order.cpp dbop.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_server.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_server.cpp
moc_server.cpp: /usr/local/qt/5.6/gcc_64/include/QtCore/QObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonvalue.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonValue \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonDocument \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsondocument.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonArray \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonarray.h \
		server.h
	/usr/local/qt/5.6/gcc_64/bin/moc $(DEFINES) -I/usr/local/qt/5.6/gcc_64/mkspecs/linux-g++ -I/home/test999/pro/kkServer3 -I/usr/local/qt/5.6/gcc_64/include -I/usr/local/qt/5.6/gcc_64/include/QtGui -I/usr/local/qt/5.6/gcc_64/include/QtNetwork -I/usr/local/qt/5.6/gcc_64/include/QtSql -I/usr/local/qt/5.6/gcc_64/include/QtCore server.h -o moc_server.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/local/qt/5.6/gcc_64/include/QtCore/QCoreApplication \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qeventloop.h \
		server.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonvalue.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonValue \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonDocument \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsondocument.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonArray \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

server.o: server.cpp def.h \
		server.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonObject \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonvalue.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonValue \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonDocument \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsondocument.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QJsonArray \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qjsonarray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QCryptographicHash \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcryptographichash.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QDateTime \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qdatetime.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhash.h \
		unit.h \
		log.h \
		order.h \
		dbop.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlDatabase \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqldatabase.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsql.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlQuery \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqlquery.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlError \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqlerror.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o server.cpp

log.o: log.cpp log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o log.cpp

order.o: order.cpp order.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o order.o order.cpp

dbop.o: dbop.cpp dbop.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlDatabase \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqldatabase.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstring.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qchar.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qflags.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsql.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlQuery \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqlquery.h \
		/usr/local/qt/5.6/gcc_64/include/QtSql/QSqlError \
		/usr/local/qt/5.6/gcc_64/include/QtSql/qsqlerror.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/QDebug \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qdebug.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhash.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qpair.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmap.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qtextstream.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qiodevice.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qlocale.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvariant.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qvector.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qpoint.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qset.h \
		/usr/local/qt/5.6/gcc_64/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbop.o dbop.cpp

moc_server.o: moc_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_server.o moc_server.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

